### ISSUE TITLE
support for custom port

### ISSUE THREAD

**Issue by mlist** [CompEpigen/FactorViz#40]
It would be great if FactorViz would not hardcode the port shiny is using but expose it as a parameter in startFactorViz(). For example, if several Rstudio server users want to start the app simultaneously this fails as the port is already in use. Simply changing to another port would solve this issue.

**Comment by lutsik** [comment]
Thanks, Markus, great point, I was pretty certain we had the port configurable. 

I committed an ad hoc fix to the devel branch, @schmic05 could you please test/merge it into master?

**Comment by schmic05** [comment]
Thanks Markus for the suggestions. We solved it with the current commit in the #devel branch.

@lutsik Thanks for merging.
